let input1 = document.getElementById("text1")
let input2 = document.getElementById("text2")
function perrs(){
    input2.innerHTML = input1.value
    .replace(/فلسطين/g, "ف/ل-سط-ي-ن")
    .replace(/اسرائيل/g,"اس-ا-ئي/ل")
    .replace(/خنازير/g,"خ/ن-ا-ز-ي-ر")
    .replace(/غزه|غزة/g,"غ-ز-ه")
    .replace(/حماس/g,"ح-م-ا-س")
    .replace(/مقاومه|مقاومة/g,"م-ق-او-م-ة")
    .replace(/فتح/g,"ف-ت-ح")
    .replace(/صاروخ/g,"ص-ا-ر-و-خ")
    .replace(/الفوسفات الأبيض|الفوسفات الابيض/g,"الف-وس-فا-ت الا-ب--ض")
    .replace(/سلاح/g,"س-لا-ح")
    .replace(/اسلحة|اسلحه/g,"اس-ل-حة")
    .replace(/حرب/g,"ح/ر/ب")
    .replace(/حروب/g,"ح/ر/و/ب")
    .replace(/قتل/g,"ق-ت-ل")
    .replace(/قتال/g,"ق-ت-ا-ل")
    .replace(/غاره|غارة/g,"غ-ا-ر-ة")
    .replace(/غارات/g,"غ-ا-ر-ا-ت")
    .replace(/قصف/g,"ق-ص-ف")
    .replace(/كتائب/g,"ك-ت-ا-ئ-ب")
    .replace(/كتيبه|كتيبة/g,"ك-تي-به")
    .replace(/كتائب القسام|كتايب القسام/g,"كت-ائب ال-ق-سام")
    .replace(/القسام/g,"ال-قس-ام")
    .replace(/حزب/g,"حز-ب")
    .replace(/دمر/g,"دمر")
    .replace(/دمار/g,"دم-ار")
    .replace(/تدمير/g,"ت-د-مير")
    .replace(/الكيان/g,"الكي-ان")
    .replace(/الصهيوني/g,"الص-ه-ي-وني")
    .replace(/بني صهيون/g,"بني صهيون")
    .replace(/يهود|اليهودي/g,"الي/ه/ود")
    .replace(/فصائل/g,"فص/ا/ئل")
    .replace(/فصيل/g,"فص/ي/ل")
    .replace(/اسرائيلي|اسرائيلى/g,"اس-را/ئي-لي")
    .replace(/اسرائليون/g,"اسرا/ئ-ل/يون")
    .replace(/اسرائليين/g,"اسر-ائ-لي/ين")
    .replace(/اسرائليات/g,"اس-رائ/لي-ات")
    .replace(/عسكرى|عسكري/g,"عسك/ر-ي")
    .replace(/عسكريون/g,"عسك-ري/ون")
    .replace(/عسكريين/g,"عسك/ر/ي-ين")
    .replace(/جنود/g,"ج-ن/ود")
    .replace(/مجندون/g,"مجن-د/ون")
    .replace(/مجندات/g,"مج/ن-دات")
    .replace(/جندي|جندى/g,"جن/د/ى")
    .replace(/حملات/g,"ح/مل-ات")
    .replace(/مناورات/g,"من/ا-ور/ات")
    .replace(/سجن/g,"س/ج-ن")
    .replace(/رهائن/g,"ره/ائ-ن")
    .replace(/قتل/g,"ق/ت-ل")
    .replace(/قتيل/g,"ق/تي/ل")
    .replace(/ذبح/g,"ذ-ب-ح")
    .replace(/دبح/g,"د/ب/ح")
    .replace(/تفجير/g,"ت/فج/ير")
    .replace(/هفجرك/g,"هف-ج/رك")
    .replace(/هدبحك/g,"هد/ب-حك")
    .replace(/الاقصي|الاقصى|الأقصي|الأقصى/g,"الا-ق-ص-ي")
    .replace(/صواريخ/g,"صو-ار-ي-خ")
    .replace(/طوفان/g,"طو-ف/ان")
    .replace(/يهودي|يهودى/g,"ي-هو-دي")
    .replace(/قنابل/g,"قن-ا-بل")
    .replace(/تهجير/g,"ت/هج/ير")
    .replace(/إباده|إبادة|اباده|ابادة/g,"اب-ا-ده")
    .replace(/جماعية|جماعيه/g,"جم-اع-ي-ه")
    .replace(/مجزره|مجزرة/g,"م-جز-ر-ه")
    .replace(/سكان/g,"س/ك/ان")
    .replace(/جنوب/g,"ج/نو/ب")
    .replace(/اسرى|اسري/g,"اس/ر/ي")
    .replace(/الاسري|الاسرى/g,"الا/سر/ى")
    .replace(/اسير|أسير/g,"اس/ي/ر")
    .replace(/اسري|أسري|اسرى|أسرى/g,"اس/ر/ي")
    .replace(/أليهودي/g,"ال-يه-ود-ي")
    .replace(/جهاد/g,"ج-ه-ا-د")
    .replace(/الجهاد|ألجهاد/g,"ال-ج-ه-اد")
    .replace(/شهيد/g,"ش-ه-ي-د")
    .replace(/الشهداء|ألشهداء/g,"ال-شه-دا-ء")
    .replace(/قتال/g,"ق-ت-ال")
    .replace(/احتلال/g,"احت-ل-ال")
    .replace(/تحرير/g,"ح-م-اس")
    .replace(/الضفة|الضفه/g,"ا-ل-فه")
    .replace(/رام/g,"ر-ا-م")
    .replace(/الكفر/g,"الك-فر")
    .replace(/ألاعتداء|الاعتداء/g,"الاع--تدء")
    .replace(/العدوان/g,"العد-وا-ن")
    .replace(/ألانتهاك|الانتهاك/g,"الان-ته-اك")
    .replace(/ألاستيلاء|الاستيلاء/g,"الاس/تي/لاء")
    .replace(/السرقه|السرقة|ألسرقه|سرقه/g,"الس/ر/قة")
    .replace(/تسرق/g,"تسرق")
    .replace(/المحتلة|محتله|المحتله/g,"المح/ت/له")
    .replace(/الاراضي|ألاراضي|الاراضى|ألاراضي/g,"الا/را/ضي")
    .replace(/قذيفة|قذيفه/g,"ق/ذي/فه")
    .replace(/تقذف/g,"تق-ذ/ف")
    .replace(/ار/g,"ا-ر")
    .replace(/بي|بى/g,"ب-ى")
    .replace(/مستوطن/g,"مست-و-طن")
    .replace(/تهجير/g,"تهج-ي-ر")
    .replace(/ارهاب|إرهاب/g,"ار-ه-اب")
    .replace(/طوفان/g,"ط-وف-ان")
    .replace(/تقطيع/g,"ت-قطي-ع")
    .replace(/خنازير/g,"خن-ازي-ر")
    .replace(/عسقلان/g,"ع-سق-لان")
    .replace(/عساكر/g,"عس-ا-كر")
    .replace(/خطر/g,"خ-ط-ر")
    .replace(/عبيده|عبيدة/g,"ع-بي-ده")
    .replace(/ابو|أبو/g,"ا-ب-و")
    .replace(/إيران|ايران/g,"اي-ر-ا-ن")
    .replace(/وفاه|وفاة/g,"وف-اة")
    .replace(/قائد/g,"قا-ئ-د")
    .replace(/تسليح/g,"تس-ل-يح")
    .replace(/مجرمين/g,"م-ج-رم-ين")
    .replace(/تخريب/g,"ت-خر-ي-ب")
    .replace(/غصب/g,"غ-ص-ب")
    .replace(/عربيه|عربية/g,"عر-ب-ية")
    .replace(/انفجار/g,"انف-ج-ار")
    .replace(/معبر/g,"مع/ب/ر")
    .replace(/رفح/g,"رف/ح")
    .replace(/الإسلام|ألاسلام|الاسلام/g,"الاس/لا/م")
    .replace(/حرق/g,"حرق")
    .replace(/الأقصي|الاقصى|الأقصى|الاقصي/g,"الاق/ص/ي")
    .replace(/جرحي/g,"ج/ر/حي")
    .replace(/الدين/g,"ال/دي/ن")
    .replace(/المسجد/g,"الم/سج/د")
    .replace(/تحرير/g,"ت/حري/ر")
    .replace(/احرار|أحرار/g,"ا/حرا/ر")
    .replace(/هتك/g,"ه/ن/ك")
    .replace(/دم/g,"د/م")
    .replace(/ابادة|اباده/g,"ابا/ده")
    .replace(/اسري|أسير|اسير/g,"اسي/ر")
    .replace(/قتله/g,"ق/تل/ه")
    .replace(/المسلمات/g,"ا/لم/سلم/ات")
    .replace(/السلام/g,"ال/س/ل/ام")
    .replace(/نيران|نار/g,"ن/ا/ر")
    .replace(/تحرش/g,"ت/ح/ر/ش")
    .replace(/رعب/g,"ر/ع/ب")
    .replace(/خونه/g,"خو/ن/ه")
    .replace(/خيانه|خيانة/g,"خ/ي/ان/ه")
    .replace(/اللعنه|اللعنة/g,"ا/ل/لع/نه")
    .replace(/اليهود/g,"ال/ي/ه/ود")
}
function copytaxt() {
    let inputElement = document.createElement("input");
    inputElement.value = document.getElementById("text2").innerHTML;
    document.body.appendChild(inputElement);
    inputElement.select();
    document.execCommand("copy");
    document.body.removeChild(inputElement);
    document.getElementById("copy").textContent = "تم النسخ";
  }
//   button detete 

function dellete(){
    input1.value = ""
    input2.innerHTML=""
}